#!/bin/bash

# Helper script to display useful commands
echo "═══════════════════════════════════════════════════════════════"
echo "  Python Coding Practice UI - Quick Commands"
echo "═══════════════════════════════════════════════════════════════"
echo ""
echo "To START the application:"
echo "───────────────────────────────────────────────────────────────"
echo "  cd coding-practice-ui"
echo "  source venv/bin/activate"
echo "  python3 run.py"
echo ""
echo "  Then open: http://localhost:5000"
echo ""
echo "To CREATE a new problem (interactive):"
echo "───────────────────────────────────────────────────────────────"
echo "  source venv/bin/activate"
echo "  python3 create_problem.py new"
echo ""
echo "  Or use the menu:"
echo "  python3 create_problem.py"
echo ""
echo "To LIST all problems:"
echo "───────────────────────────────────────────────────────────────"
echo "  python3 create_problem.py list"
echo ""
echo "To CONVERT existing Python scripts to problems:"
echo "───────────────────────────────────────────────────────────────"
echo "  python3 convert_problems.py <source_dir> [target_dir] [category]"
echo ""
echo "  Example:"
echo "  python3 convert_problems.py ../scripts/pythonbasics ./app/problems 'Python Basics'"
echo ""
echo "To EDIT a problem manually:"
echo "───────────────────────────────────────────────────────────────"
echo "  Edit any JSON file in: app/problems/"
echo "  Changes appear automatically when you refresh the browser"
echo ""
echo "═══════════════════════════════════════════════════════════════"
echo ""
echo "📚 For detailed documentation, see:"
echo "   - README.md       (Full documentation)"
echo "   - QUICKSTART.md   (Getting started guide)"
echo ""
echo "═══════════════════════════════════════════════════════════════"
