# from array import *
# arr = array('i', [1,2,3])
# print(arr)

from numpy import *

print()
print("Numpy Array Creation - Question 1")
print("Create an array using 'array()' with elements 2, 4, 6, 8. Expected output: [2 4 6 8]")
arr = array([2, 4, 6, 8])
print('Input:\n arr = array([2, 4, 6, 8])')
print('Code: \n arr = array([2, 4, 6, 8])')
print('Output:\n', arr)
print('-'*20)
print()

print("Numpy Linspace - Question 2")
print("Create an array with 'linspace()' from 0 to 4 with 5 elements. Expected output: [0. 1. 2. 3. 4.]")
arr = linspace(0, 4, 5)
print('Input:\n linspace(0, 4, 5)')
print('Code: \n arr = linspace(0, 4, 5)')
print('Output:\n', arr)
print('-'*20)
print()

print("Numpy Arange - Question 3")
print("Create an array using 'arange()' from 1 to 10 with step size 2. Expected output: [1 3 5 7 9]")
arr = arange(1, 10, 2)
print('Input:\n arange(1, 10, 2)')
print('Code: \n arr = arange(1, 10, 2)')
print('Output:\n', arr)
print('-'*20)
print()

print("Numpy Zeros - Question 4")
print("Create an array of 5 zeros using 'zeros()'. Expected output: [0. 0. 0. 0. 0.]")
arr = zeros(5)
print('Input:\n zeros(5)')
print('Code: \n arr = zeros(5)')
print('Output:\n', arr)
print('-'*20)
print()

print("Numpy Ones (Int) - Question 5")
print("Create an integer array of 4 ones using 'ones()'. Expected output: [1 1 1 1]")
arr = ones(4, int)
print('Input:\n ones(4, int)')
print('Code: \n arr = ones(4, int)')
print('Output:\n', arr)
print('-'*20)
print()


print()
print("Numpy Logspace - Question 6")
print("Create an array using 'logspace()' from 1 to 3 with 3 elements. Expected output: [10. 100. 1000.]")
arr = logspace(1, 3, 3)
print('Input:\n logspace(1, 3, 3)')
print('Code: \n arr = logspace(1, 3, 3)')
print('Output:\n', arr)
print('-'*20)
print()
