print()
print("Positional Arguments - Question 1")
print("Call the function 'greet' with positional arguments 'Alice' and 30. Expected output: Hello, Alice! You are 30 years old.")
def greet(name, age):
    print(f"Hello, {name}! You are {age} years old.")
greet('Alice', 30)
print('Input:\n greet(\'Alice\', 30)')
print('Code: \n def greet(name, age):\n    print(f"Hello, {name}! You are {age} years old.")\ngreet(\'Alice\', 30)')
print('Output:\n Hello, Alice! You are 30 years old.')
print('-'*20)
print()

print("Keyword Arguments - Question 2")
print("Call the function 'greet' using keyword arguments. Expected output: Hello, Bob! You are 25 years old.")
greet(age=25, name='Bob')
print('Input:\n greet(age=25, name=\'Bob\')')
print('Code: \n greet(age=25, name=\'Bob\')')
print('Output:\n Hello, Bob! You are 25 years old.')
print('-'*20)
print()

print("Default Arguments - Question 3")
print("Call the function 'greet' with default age. Expected output: Hello, Charlie! You are 30 years old.")
def greet(name, age=30):
    print(f"Hello, {name}! You are {age} years old.")
greet('Charlie')
print('Input:\n greet(\'Charlie\')')
print('Code: \n greet(\'Charlie\')')
print('Output:\n Hello, Charlie! You are 30 years old.')
print('-'*20)
print()

print("Variable Length Arguments - Question 4")
print("Call the function 'sum_numbers' with variable length arguments. Expected output: Sum: 15")
def sum_numbers(*args):
    print("Sum:", sum(args))
sum_numbers(1, 2, 3, 4, 5)
print('Input:\n sum_numbers(1, 2, 3, 4, 5)')
print('Code: \n sum_numbers(1, 2, 3, 4, 5)')
print('Output:\n Sum: 15')
print('-'*20)
print()

print("Keyword Variable Length Arguments - Question 5")
print("Call the function 'person_data' with keyword variable length arguments. Expected output: Name: Dave, Age: 40, City: New York")
def person_data(name, **data):
    print("Name:", name)
    for key, value in data.items():
        print(key.title() + ":", value)
person_data('Dave', age=40, city='New York')
print('Input:\n person_data(\'Dave\', age=40, city=\'New York\')')
print('Code: \n person_data(\'Dave\', age=40, city=\'New York\')')
print('Output:\n Name: Dave, Age: 40, City: New York')
print('-'*20)
print()
